### ISSUE TITLE
Polymorphic classes are missing type parameters

### ISSUE THREAD

**Issue by yungsters** [babel-plugins/babel-plugin-flow-comments#15]
For the following input:

```
class Deferred<Tx, Ty> {}
```

I expect the following output:

```
"use strict";

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Deferred = function Deferred /*:: <Tx, Ty>*/() {
  _classCallCheck(this, Deferred);
};
```

Currently, ` /*:: <Tx, Ty>*/` is missing from the definition of `Deferred`.

**Comment by sebmck** [comment]
This would actually be a Babel core issue since the nodes are just being lost. I'm not sure what to do about this since `typeParameters` **can** be retained but AFAIK there'd be no way to express other type information on the class such as `superTypeParameters` and `implements`.

**Comment by sebmck** [comment]
Nevermind, didn't realise `implements` wasn't supported in Flow yet. Not sure what's consequence of losing `superTypeParameters` though.

**Comment by yungsters** [comment]
I suspect the consequence of losing `superTypeParemeters` would be not being able to handle the following:

```
class Visitor<Ts> {
}
class Transform<Ts> extends Visitor<Ts> {
}
```

**Comment by sebmck** [comment]
Could that be expressed with a `declare class` in any way? Might be worth desugaring classes differently in order to retain all the correct type info. Could possibly also help with Flow not being able to understand the shape of Babel compiled classes. (FWIW my knowledge of how flow types actually work is extremely minimal, I just know the syntax parses...)
