### ISSUE TITLE
Error when running on latest Babel

### ISSUE THREAD

**Issue by leebyron** [babel-plugins/babel-plugin-flow-comments#8]
Error: /Users/leebyron/src/graphql-js/src/type/definition.js: You passed `path.replaceWith()` a falsy node, use `path.dangerouslyRemove()` instead.

Seems to start with https://github.com/babel-plugins/babel-plugin-flow-comments/blob/master/src/index.js#L15

**Comment by hzoo** [comment]
Hmm weird - didn't get that issue running the tests - will look into it

**Comment by hzoo** [comment]
@leebyron ok it's because of `export type x`. I only added tests for `type x`.

```js
// example
export type GraphQLFormattedError = {
  message: string,
  locations?: Array<{
    line: number,
    column: number
  }>
};
```

@sebmck is there an easy way to use/call another visitor function? Like if in the visitor for `ExportNamedDeclaration` I want to use the same function as the `Flow` one `if (t.isFlow(node.declaration))`

I guess I could do `"ExportNamedDeclaration|Flow"` and then return early if the condition is false?

```js
"ExportNamedDeclaration|Flow"(node, parent, scope, file) {
        if (t.isExportNamedDeclaration(node) && !t.isFlow(node.declaration)) {
          return;
        }
  ...
}
```
